### ISSUE TITLE
Array of Struct object

### ISSUE THREAD

**Issue by xie-samuel** [symentis/Palau#13]
Any idea how I can make PalauDefaultable for an array of the following struct?

public struct Person {
    var name: String?
    var address: String?
    var state: String?
    var zipcode: String?
}

Thanks

**Comment by elm4ward** [comment]
We will have a look! 

One possible workaround is to use a Wrapper struct.
(As we cannot yet use Conditional conformances like
`extension Array : Equatable where Element : Equatable { })`)
But of course that`s not really nice workaround.

**Comment by elm4ward** [comment]
I added a branch for dedicated Array handling:

https://github.com/symentis/Palau/tree/feature-arrays
https://github.com/symentis/Palau/blob/feature-arrays/PalauTests/PalauDefaultsArrayTest.swift

In this branch you can add a  PalauDefaultsArrayEntry like

```
public static var structsWithTuple: PalauDefaultsArrayEntry<Structy> {
  get { return value("structies") }
  set { }
}
```

The mapping in the current version is verbose, but we will probably find an easier way ... 

```
extension Structy: PalauDefaultable {

  private static func toDict(from s: Structy) -> [String: AnyObject] {
    return ["1": s.tuple.0, "2": s.tuple.1]
  }

  private static func fromDict(dict: [String: AnyObject]) -> Structy? {
    guard let t1 = dict["1"] as? String,
      t2 = dict["2"] as? String else { return nil }
    return Structy(tuple: (t1, t2))
  }

  public static func get(key: String, from defaults: NSUD) -> Structy? {
    guard let d = defaults.objectForKey(key) as? [String: AnyObject] else { return nil }
    return fromDict(d)
  }

  public static func get(key: String, from defaults: NSUD) -> [Structy]? {
    guard let d = defaults.objectForKey(key) as? [[String: AnyObject]] else { return nil }
    return d.flatMap(fromDict)
  }

  public static func set(value: Structy?, forKey key: String, in defaults: NSUD) -> Void {
    guard let value = value else { return defaults.setObject(nil, forKey: key) }
    defaults.setObject(toDict(from: value), forKey: key)
  }

  public static func set(value: [Structy]?, forKey key: String, in defaults: NSUD) -> Void {
    guard let value = value else { return defaults.setObject(nil, forKey: key) }
    defaults.setObject(value.map(toDict), forKey: key)
  }
}
```

**Comment by elm4ward** [comment]
All Tests for PalauDefaultsArrayEntry passed. =)
https://travis-ci.org/symentis/Palau/builds/127993435

**Comment by elm4ward** [comment]
In the branch feature-arrays there is an update.

You can use a new protocol for easier conversion:

```
extension Structy: PalauCustomDefaultable {

  public static func toIntermediate(s: Structy) -> [String: AnyObject] {
    return ["1": s.tuple.0, "2": s.tuple.1]
  }

  public static func fromIntermediate(dict: [String: AnyObject]) -> Structy? {
    guard let t1 = dict["1"] as? String, t2 = dict["2"] as? String else { return nil }
    return Structy(tuple: (t1, t2))
  }

}
```

You should be able to use the Struct as 
- PalauDefaultsEntry
- PalauDefaultsArrayEntry

Ist this solution working for you? 
We still have to do more testing before merging onto master, but Tests passed locally. 👍

**Comment by elm4ward** [comment]
We got #15

**Comment by xie-samuel** [comment]
It is worked. Thanks for your help

**Comment by madhavajay** [comment]
Looks like this can be closed now. 👍
