### ISSUE TITLE
PalauDefaultable mapping simplification?

### ISSUE THREAD

**Issue by elm4ward** [symentis/Palau#14]
Wouldn`t it be sufficient when all we need to define is:

```
public protocol PalauDefaultable {

  /// The associatedtype for the Value
  associatedType ValueType

  public static func from(any: AnyObject?) -> ValueType?
  public static func to(any:ValueType?) -> AnyObject?
}
```

Is it worth going down that path or should we live with the current implementation until Swift 3 is available?

See:
#13

**Comment by elm4ward** [comment]
WIP: 

https://github.com/symentis/Palau/commit/f61f9b07372f2bc9dad44bd3d7dd198bfd372b63

We should discuss naming of types:

**PalauDefaults**
- Basic Wrapper

**PalauDefaultable**
- Protocol for types that can be stored to defaults

**PalauCustomDefaultable**
- Protocol for custom types that provides a mapping for storing

**PalauEntry**
- Protocol for entries 

**PalauDefaultsEntry**
- Struct for getting / setting a single value 

**PalauDefaultsArrayEntry**
- Struct for getting / setting a list of values

**Comment by madhavajay** [comment]
As swift 4 makes this library somewhat obsolete I will close this issue.
