### ISSUE TITLE
Swift 3.0 support. Anyone?

### ISSUE THREAD

**Issue by amcuserguy** [symentis/Palau#22]

**Comment by madhavajay** [comment]
We have a branch:
https://github.com/symentis/Palau/tree/swift-3

There are a few outstanding issues and improvements to make and then we will merge the Swift 3 branch into master, possibly tracking an old swift-2 branch with the current master version.

**Comment by madhavajay** [comment]
We now have swift-4 support thanks to @ksmandersen, so im going to close this.
