### ISSUE TITLE
Feature Request: didSet

### ISSUE THREAD

**Issue by elm4ward** [symentis/Palau#5]
It would be nice to add a didSet callback like on a regular property. 
The function should provide the old value and the new.

**Comment by elm4ward** [comment]
Added new branch feature-didSet

**Comment by elm4ward** [comment]
In my opinion it does not make sense to add multiple didSet on a property. 
Therefore I propose that the callback for didSet cannot be chained.

**Comment by madhavajay** [comment]
Looks great! Merged. :)
